# Generated by Django 6.0.3 on 2026-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_assigned_users_todo_owner_alter_todo_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['priority', '-id']},
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
